export const getIsLogIn = state => state.auth.isLoggedIn;
export const getName = state => state.auth.user.name;
export const getEmail = state => state.auth.user.email;
export const getToken = state => state.auth.token;
export const getContacts = state => state.contacts.contacts;
export const getLoading = state => state.auth.loading;
export const getLoadingContacts = state => state.contacts.loadingContact;
export const getColor = state => state.color;
export const getFilter = state => state.filter;
